✨ Add last_modified_at field to more models & expose updated field
okfde/froide pull request #723
Opened 2023-11-20 14:21 UTC by pajowu

2023-11-30 09:02 UTC, stefanw requested changes

2023-11-30 09:02 UTC, stefanw commented on froide/publicbody/api_views.py
> +            "updated",
Maybe for consistency the field should be called the same as for the others? So expose a different name than the database field name.

2023-12-18 17:24 UTC, pajowu commented on froide/foirequest/migrations/0065_foimessage_last_modified_at_and_more.py
> +            field=models.DateTimeField(auto_now=True),
I wasn't sure about a good default either, but recalculating this from the FoiEvents seems a too big of an effort for no real gain IMHO

2024-01-03 14:37 UTC, pajowu commented on froide/foirequest/migrations/0065_foimessage_last_modified_at_and_more.py
> +            field=models.DateTimeField(auto_now=True),
I tried implementing that but since last_modified_at is an auto_now field, that's not really possible :/

2024-01-03 14:52 UTC, merged